### ISSUE TITLE
How to get the entire string?

### ISSUE THREAD

**Issue by mc-public** [cdacamar/fredbuf#2]
Hello! I'm not sure if iterating through the entire string is the most efficient way to obtain the entire string corresponding to the PieceTree. 
```
for (char c : buf)
{
    printf("%c", c);
}
```
What is the most efficient way to obtain the entire string corresponding to the PieceTree?

**Comment by cdacamar** [comment]
The most efficient way to gather up the entire string right now is to use one of the various `PieceTree::TreeWalker` classes.  Something like this could be an efficient way to build a `std::string`:

```c++
void fill_string(std::string* str, const PieceTree::Tree& tree) {
  str->clear();
  str->reserve(rep(tree.length()));
  PieceTree::TreeWalker walker{ &tree };
  while (not walker.exhausted()) {
    str->push_back(walker.next());
  }
}
```

This way you take advantage of knowing the content length up-front.

Note: the for-each loop you have there will, essentially, do the same thing, but without the reserve.

**Comment by mc-public** [comment]
Thank you for your prompt response. I have already used the above code to obtain the entire string corresponding to the PieceTree.
